# torch.multinomial

在 PyTorch 中，`torch.multinomial` 函数是用于根据**概率分布进行采样**的工具。它接受一个包含概率的张量作为输入，并返回一个张量，其中每行包含从相应输入行的多项式概率分布中采样的 num_samples 个索引。

## 函数的基本用法
torch.multinomial 函数的基本用法如下：
```python
torch.multinomial(input, num_samples, replacement=False, *, generator=None, out=None) → LongTensor
```

## 输入参数
- input：包含概率的张量，不需要总和为一，但必须是非负的、有限的，并且总和不为零。
- num_samples：要抽取的样本数量。
- replacement：是否有放回地抽取样本。如果为 True，则允许重复抽取；如果为 False，则不允许重复抽取。
- generator：用于采样的伪随机数生成器。

## 输出
out：输出张量。






## 示例

以下是一些使用 torch.multinomial 函数的示例：

In [73]:
import torch
# 创建一个包含权重的张量
weights = torch.tensor([0.8, 0.1, 0.05, 0.01, 0.04, 0], dtype=torch.float)

# 无放回地抽取2个样本
samples = torch.multinomial(weights, 1)
print(samples)

# 无放回地抽取2个样本
samples = torch.multinomial(weights, 2)
print(samples) # 输出可能是 tensor([1, 2])

# 有放回地抽取4个样本
samples = torch.multinomial(weights, 4, replacement=True)
print(samples) # 输出可能是 tensor([2, 1, 1, 1])

tensor([0])
tensor([3, 0])
tensor([0, 0, 2, 0])


在这个例子中，权重张量 weights 表示每个元素的抽取概率。由于某些元素的权重为零，它们在其他非零元素被抽取完之前不会被抽取。当 replacement 参数设置为 False 时，num_samples 的值必须小于非零元素的数量；否则，会引发错误。



## 注意事项

当使用无放回抽样时，num_samples 必须小于输入张量中非零元素的数量。

抽取的索引是从左到右排序的，根据它们被抽取的顺序。

如果输入是向量，输出也是向量；如果输入是矩阵，输出是形状为 (m, num_samples) 的矩阵，其中 m 是输入矩阵的行数。

`torch.multinomial` 是在概率分布下进行采样的有效工具，特别是在处理诸如强化学习或随机决策过程中的随机性时。